name: lol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  file_picker: ^10.1.2
  just_audio: ^0.10.2
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  audio_session: ^0.1.10



flutter:
  uses-material-design: true
  assets:
    - assets/audios/Sanson ki mala pe remix   NFAK .mp3
    - assets/audios/Skyfall- Adele.mp3
    - assets/audios/Lana Del Rey - Young and beautiful.mp3


dev_dependencies:
  flutter_test:
    sdk: flutter


